embercli:
  image: quay.io/webcenter/ember-coder
  volumes:
    - ./ember:/node/src
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
  environment:
    - DISPLAY

emberrun:
  image: quay.io/webcenter/ember-builder
  volumes:
    - ./ember:/node/src
  ports:
    - "4200:4200"
    - "49152:49152"
  command: ember serve

gitflowcli:
  image: quay.io/webcenter/gitflow-coder
  volumes:
    - .:/workspace
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
  environment:
    - DISPLAY

nodejscli:
  image: quay.io/webcenter/nodejs-coder
  volumes:
    - ./nodejs:/node/src
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
  environment:
    - DISPLAY

nodejsrun:
  image: quay.io/webcenter/nodejs-builder
  volumes:
    - ./nodejs:/node/src
  ports:
    - "9000:9000"
  command: grunt server
  links:
    - "mongodb:db"

mongodb:
  image: mongo:3.2
  volumes:
    - ./mongo:data/db
