embercli:
  image: quay.io/webcenter/ember-coder
  volumes:
    - ./workspace:/node/src #APP_WEB
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
  environment:
    - DISPLAY

emberrun:
  image: quay.io/webcenter/ember-builder
  volumes:
    - ./workspace/APP_WEB:/node/src
  ports:
    - "4200:4200"
    - "49152:49152"
  command: ember serve

gitflowcli:
  image: quay.io/webcenter/gitflow-coder
  volumes:
    - ./workspace:/workspace
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
  environment:
    - DISPLAY

nodejscli:
  image: quay.io/webcenter/nodejs-coder
  volumes:
    - ./workspace:/node/src #APP_BACK
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
  environment:
    - DISPLAY
  links:
    - "mongodb:db"

nodejsrun:
  image: quay.io/webcenter/nodejs-builder
  volumes:
    - ./workspace/APP_BACK:/node/src
  ports:
    - "9000:9000"
  command: grunt server
  links:
    - "mongodb:db"

mongodb:
  image: mongo:3.2
  volumes:
    - ./mongo:/data/db
